routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('comercio', function(){
    return View('comercio');
});
//Actividad
Route::resource('actividad', 'actividadController');
//Comunero
Route::resource('comunero', 'comuneroController');
Route::get('list', 'comuneroController@imprimir');
Route::get('infouser', 'comuneroController@infouser');
//Asistencia
Route::resource('asistencia', 'asistenciaController');

resources/views/comercio.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="card" style="width: 18rem;">
            <img src="..." class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title">Card title</h5>
              <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              <a href="#" class="btn btn-primary">Go somewhere</a>
            </div>
          </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
        <a type="button" href="{{ route('actividad.index') }}">
            <button type="button" class="btn btn-primary">Actividades <i class="fas fa-list-ul"></i></button>
        </a>    
        <a type="button" href="{{ route('actividad.index') }}">
            <button type="button" class="btn btn-primary">Solicitudes <i class="fas fa-align-center"></i></button>
        </a>  
        <a type="button" href="{{ route('comunero.index') }}">
            <button type="button" class="btn btn-primary">Comuneros <i class="fas fa-users"></i></button>
        </a>
        <a type="button" href="{{ route('asistencia.index') }}">
            <button type="button" class="btn btn-primary">Asistencia <i class="fas fa-tasks"></i></button>
        </a>
        <div class="btn-group" role="group">
            <button id="btnGroupDrop1" type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown
            </button>
            <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                <a class="dropdown-item" href="#">Dropdown link</a>
                <a class="dropdown-item" href="#">Dropdown link</a>
            </div>
        </div>
    </div>
    <hr>
</div>
@endsection